version: '3.5'
services:
  midia-debug:
    build: .
    volumes:
      - .:/var/www/gateway
    restart: always
    hostname: midia
    command: npm run start:debug
    ports:
      - 9225:9225
    env_file:
      - .env
      - .cloudinary.env
    networks:
      - backend
  midia-dev:
    build: .
    volumes:
      - .:/var/www/gateway
    restart: always
    hostname: midia
    command: npm run start:dev
    env_file:
      - .env
      - .cloudinary.env
    networks:
      - backend

networks:
  backend:
    external:
      name: cartografia-network